### PR TITLE
Implemented Forgot Password Functionality

### PR DESCRIPTION
**Pull request by jpoist97**
Implemented forgot password functionality and frontend flow and Cognito flow
Screen Shot 2022-01-19 at 2 27 56 PM
Screen Shot 2022-01-19 at 2 28 16 PM
Screen Shot 2022-01-19 at 2 28 34 PM

### CODE REVIEW

**Review by ctperry0301 — COMMENTED** [review]
Overall the forgot password flow works great. I was able to successfully reset my password. saying that, I received this error message after my password was reset.

It looks like it might be an error with the PasswordResetSuccess
Screen Shot 2022-01-19 at 8 14 07 PM
4

**Comment by jpoist97** [comment]
I'm going to look into this more, but this looks like an error associated with Rohith's Post Confirmation Lambda function that just got deployed

**Comment by jpoist97** [comment]
Issue should be fixed now @ctperry0301, looks like the Cognito Post Confirmation Trigger was pointing to the wrong Lambda function

**Comment by jpoist97** [comment]
This might be an issue going forward though, since it looks like the lambda might have slightly been renamed the last time the SAM template was deployed. Cause the lambda previously set to run on Post confirmation no longer existed

**Pull request merged**
